### ISSUE TITLE
display of <lb/> to be made context independent

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#187]
the fact that `<lb>` figures in a larger `<foreign>` context, as in the screenshot below, should not cause the display of the line numbers to become italic. can you solve this, @ajaniak ? thanks!

<img width="713" alt="Capture d’écran 2022-11-26 à 18 55 34" src="https://user-images.githubusercontent.com/835603/204087643-85ad6e89-8163-4f6f-b853-84bb4923da0f.png">

**Comment by ajaniak** [comment]
Done, since it is processed thought the CSS, it might take some time to be applied.

**Comment by arlogriffiths** [comment]
at the moment I still see italics. I will try again tomorrow.

**Comment by arlogriffiths** [comment]
I still see italics on line numbers 12, 13 and 14 at [https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/Java10Majapahit/DHARMA_INSIDENKKedungwangi.html](url).
