### ISSUE TITLE
<lb> not correctly displayed 

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#212]
<img width="218" alt="Capture d’écran 2023-04-19 à 11 30 51" src="https://user-images.githubusercontent.com/835603/232971968-0b3b2592-591e-4618-a30a-41db176fe689.png">

**Comment by ajaniak** [comment]
which edition?

**Comment by arlogriffiths** [comment]
https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/DHARMA_INSIDENKTija-HaruHaru.html

**Comment by arlogriffiths** [comment]
but I have seen the problem occur also in other html in recent days

**Comment by ajaniak** [comment]
I have pushed a new CSS at the beginning of the week. So a problem might have occurred at that moment. But it should be resolved since yesterday. Can you refresh the page? 
Because on my side, I have this 
![Capture d’écran 2023-04-19 à 12 10 43](https://user-images.githubusercontent.com/33328906/233043653-cf8cd220-f718-4ab5-baad-77e9e9f7d083.png)

**Comment by arlogriffiths** [comment]
I still have this (in Firefox)

<img width="849" alt="Capture d’écran 2023-04-19 à 17 13 39" src="https://user-images.githubusercontent.com/835603/233044080-07ac9cfa-4eb3-44ca-93f2-08c53a589cf9.png">

**Comment by arlogriffiths** [comment]
and the problem seems to appear in all htlms on my side (at least all those that I've checked). here's an instance from Masahar.

![Uploading Capture d’écran 2023-04-19 à 17.14.59.png…]()

**Comment by ajaniak** [comment]
It is difficult for me to figure out your issue, since I can't reproduce the issue

**Comment by arlogriffiths** [comment]
the problem seems to be browser related, because display is normal on Chrome and Safari, but remains wrong on Firefox. dis display correct on your side when you use Firefox?

**Comment by arlogriffiths** [comment]
cleaned and problem solved! thanks!
